<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PackageId>viwik.$(AssemblyName)</PackageId>
    <Version>1.0.1</Version>
    <Authors>vi-wik</Authors>
    <RepositoryUrl>https://github.com/vi-wik/EnglishLearning</RepositoryUrl>
    <Description>英语学习业务层</Description>
    <PackageReleaseNotes>bug修复：获取单词结构时某些情况字典重复添加键</PackageReleaseNotes>
    <AssemblyVersion>1.0.1</AssemblyVersion>
    <FileVersion>1.0.1</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EnglishLearning.DataAccess\EnglishLearning.DataAccess.csproj" />
    <ProjectReference Include="..\EnglishLearning.Model\EnglishLearning.Model.csproj" />
  </ItemGroup>

</Project>
